ashdod = {'Big Fashion Mall Ashdod': '₪0',
          'The Eye of the Sun': '₪0'}

arad = {'Safsal Perfect Nof': '₪0',
        'Masada Fortress': '₪0',
        'Mo\'av Observation Point': '₪0'}

bat_yam = {'Bat Yam Boardwalk-Tayelet': '₪0',
           'Michal Negrin\'s World': '₪0',
           'RSQ - Real Story Quest': '₪0',
           'Fifth Element - Escape Room': '₪0',
           'Dekel Club - Billiard Snooker Bar & Bowling': '₪0',
           'ShareSpa Leonardo': '₪0'}

beer_sheva = {'Negev Zoo': '₪30',
              'Zin River': '₪0',
              'Grand Canyon Shopping Mall': '₪0',
              'Monument to the Negev Brigade': '₪0',
              'Abraham\'s Well International Visitor Center': '₪0',
              'Tel Be\'er Sheva National Park': '₪0',
              'Mitzpe Beit Eshel': '₪0',
              'Big Beer Sheva': '₪0',
              'Escape Room Beer Sheva': '₪70',
              'Exit Room': '₪70',
              'Gameon - Escape Rooms': '₪70'}

eilat = {'Isrotel Theatre': '₪0',
         'Musical Fountain': '₪0',
         'Botanical Garden Of Eilat': '₪0',
         'Camel Ranch Eilat': '₪0',
         'Eilat Marina': '₪0',
         'Hai Bar - Wildlife Reserve': '₪0',
         'King Solomon\'s Mines': '₪0',
         'Mount Yoash Observation Point': '₪0',
         'Ammerm columns': '₪0',
         'Ice Mall': '₪0',
         'Mall Hayam': '₪0',
         'Har Cfachot': '₪0'}

jerusalem = {'Old City of Jerusalem': '₪0',
             'Western Wall': '₪0',
             'Monte das Oliveiras': '₪0',
             'Église du Saint-Sépulcre': '₪0',
             'The Western Wall Tunnels': '₪0',
             'Mahane Yehuda Market': '₪0',
             'The Garden Tomb': '₪0',
             'Garden of Gethsemane': '₪0',
             'Hezekiah\'s Tunnel - Siloam Tunnel': '₪0',
             'The Way of the Cross - Via Dolorosa': '₪0',
             'Church of All Nations': '₪0',
             'Jewish Quarter': '₪0',
             'Church of Saint Anne': '₪0',
             'Christ\'s Tomb': '₪0',
             'Mamilla Mall': '₪0',
             'Ben Yehuda Street': '₪0',
             'The Cardo': '₪0',
             'The First Station Jerusalem': '₪0',
             'Hurva Synagogue': '₪0'}

netanya = {'Inter Active Atzmaut Square': '₪0',
           'Victory Monument': '₪0',
           'Ir Yamim Mall': '₪0',
           'Shefayim Water Park': '₪50',
           'Splinter': '₪0',
           'Antique & Collectors Weekly Market': '₪0',
           'Yechin Alexandra Center': '₪0',
           'Hamei Ga\'ash': '₪60',
           'Gal Yam Surf School': '₪0',
           '7 Winds Tandem Paragliding': '₪0',
           'PuzzleBox - Escape Rooms': '₪60',
           'Placebo Escape Room': '₪60',
           'Escape Room Heroes - Brainit': '₪60',
           'No Exit - Escape Room': '₪60',
           'Laser Tag Poleg': '₪70',
           'Via Maris Spa': '₪200'}

ramat_gan = {'Ramat Gan Safari': '₪60',
             'Ayalon Mall': '₪0',
             'Zoological Center': '₪0',
             'Elram Mall': '₪0',
             'Savransky Private Jeweler': '₪0',
             'Secret Area Escape Room': '₪70',
             'Exit Room': '₪70',
             'Lol & Pop - Candy Making Master Class': '₪70',
             'Ramat gan bowling': '₪60'}

tel_aviv = {'Tayelet': '₪0',
            'Neve Tzedek': '₪0',
            'Jaffa Old City': '₪0',
            'Carmel Market (Shuk Ha\'Carmel)': '₪0',
            'Sarona Market': '₪0',
            'Nachalat Binyamin Pedestrian Mall': '₪0',
            'Old Tel Aviv Port Area': '₪0',
            'Rothschild Boulevard': '₪0',
            'Palmach Museum': '₪0',
            'Florentine': '₪0',
            'Ben-Gurion House': '₪0',
            'Suspended Orange Tree': '₪0',
            'White City': '₪0',
            'Jaffa Flea Market': '₪0',
            'Saint Peter Church': '₪0',
            'Dizengoff Center': '₪0',
            'Levinsky Market': '₪0',
            'Kikar Kedumim-Old Jaffa': '₪0',
            'Clock Tower': '₪0',
            'Itzhak Rabin Monument': '₪0'}

tsfat = {'The Old City of Safed': '₪0',
         'Abuhav Synagogue': '₪0',
         'Bat Ya\'ar Ranch': '₪0',
         'The Ashkenazi HaAri Synagogue': '₪0',
         'Soul and Art Fine Art Gallery': '₪0',
         'The Abouhav Winery': '₪0',
         'Yosef Caro Synagogue': '₪0',
         'The Sephardic Synagogue of the Ari': '₪0',
         'The Tzfat Kabbalah Experience': '₪0',
         'Kadosh Cheese Factory': '₪0',
         'Sheva Chaya Glassblowing Gallery': '₪0'}

tveria = {'Sea of Galilee': '₪0',
          'Tabgha': '₪0',
          'Jordan River Village': '₪0',
          'Domus Galilaeae': '₪0',
          'Berenice Winery': '₪0',
          'Tiberias': '₪0',
          'Aqua Kef': '₪0',
          'Tiberias Hot Springs': '₪0',
          'Kibbutz Degania Alef': '₪0',
          'Tomb of Rabbi Meir': '₪0',
          'Tomb of Maimonides': '₪0',
          'Ginosar Village': '₪0',
          'Arbel Cliff': '₪0',
          'Gai Beach Water Park': '₪0'}

haifa = {'Hanging Bridge': '₪0',
         'The Baha\'i Gardens': '₪0',
         'The German Colony': '₪0',
         'Stella Maris Lighthouse and Carmelite Monastery': '₪0',
         'Yefe Nof Street': '₪0',
         'Wadi Nisnas': '₪0',
         'Haifa Port': '₪0',
         'Haifa Educational Zoo': '₪0',
         'Ein Hod Artists Village': '₪0',
         'Sculptures Garden': '₪0',
         'Aerial Cable Car': '₪0',
         'Cave of Elijah': '₪0',
         'Grand Canyon Mall': '₪0',
         'Sammy Ofer Stadium': '₪0',
         'Haifa University': '₪0',
         'Jordan River Village': '₪0'}
