ashdod = {'Gambrinus': '₪80',
          'Idi': '₪80',
          'Castle Bar Ashdod': '₪80',
          'Pescado Fish Restaurant': '₪70',
          'Pinta': '₪70',
          'Endive': '₪80',
          'Kira': '₪70',
          'Aramis': '₪80',
          'pavella': '₪70',
          'Goda': '₪80'}

arad = {'Kaparuchka': '₪60',
        'Muza': '₪60',
        'Lenagev BaNegev': '₪60',
        'Aradika': '₪60'}

bat_yam = {'Wine N\' Dine': '₪80',
           'Rubin Cafe': '₪50',
           'Fish': '₪75',
           'Tampopo Sushi Bar': '₪80',
           'Villa Mare': '₪75',
           'Onza': '₪80',
           'Basma Coffee': '₪65',
           'OCD Restaurant': '₪80',
           'Puaa': '₪80',
           'Jopea Kitchen Bar': '₪75'}

beer_sheva = {'Saba Jebeto': '₪60',
              'Bbb-Burgus Burger Bar': '60',
              'Nafis': '₪60',
              'Hasifriya': '₪65',
              'Kampai Sushi Grill': '₪80',
              'Albi': '₪60',
              'Pastina': '₪65',
              '55 Beers and food': '₪60',
              'Kepasa': '₪60',
              'Caldo': '₪60'}

eilat = {'Pastory': '₪75',
         'Omer\'s': '₪56',
         'Pitagoras': '₪60',
         'Rak Dagim': '₪75',
         'Les Sardines': '₪65',
         'Branja': '₪60',
         '9 Beach Eilat': '₪70',
         'Torta': '₪75',
         'Little Brazil': '₪80',
         'Papi Grill': '₪65'}

jerusalem = {'Atalya': '₪65',
             'Sarwa Street Kitchen': '₪70',
             'Deja Bu': '₪70',
             'Blue Hall Music': '₪65',
             'Mirror Bar': '₪70',
             'Rooftop': '₪75',
             'Etz Cafe': '₪75',
             'Nah\'man Restaurant': '₪80',
             'Jahnun Bar': '₪60',
             'Katy\'s': '₪75'}

netanya = {'Uzi Hummus Ful': '₪75',
           'Ni-Shi': '₪75',
           'Alabama': '₪70',
           'The Scotsman': '₪80',
           'Mojo Asian Foodbar': '₪75',
           'B12 poleg Station': '₪70',
           'Fat Vinny': '₪65',
           'Marrakesh': '₪80',
           'Jacko': '₪70',
           'El Gaucho': '₪85'}

ramat_gan = {'Jem\'s Beer Factory': '₪70',
             'Kisu': '₪70',
             'Goomba': '₪75',
             'Origem Fresh Coffee': '₪70',
             'Golda': '₪80',
             'Dede bar': '₪75',
             'Arte Italian Ice Cream': '₪60',
             'Frishman Falafel & Frishman Sabich': '₪60',
             'Topolopompo': '₪65',
             'Hudson Restaurant': '₪70'}

tel_aviv = {'Mashya': '₪70',
            'Topolopompo': '₪75',
            'Origem Fresh Coffee': '₪70',
            'SABICH TSERNIKOVSKI': '₪80',
            'Bar Ochel': '₪80',
            'Night Kitchen': '₪75',
            'Balinjera': '₪80',
            'West Side': '₪85',
            'Beer Bazaar': '₪85',
            'Bicicletta': '₪80'}

tsfat = {'Elements Cafe Tzfat': '₪75',
         'HaAri 8': '₪80',
         'Bat Yaar': '₪75',
         'Cafe Monitin': '₪70',
         'Tree of Life Vegetarian Cafe': '₪70',
         'Seudat Gan Eden': '₪70',
         'Art Coffee Mikael': '₪80',
         'Kvish 90': '₪70',
         'Shokolata': '₪65',
         'Bella Cafe': '₪60'}

tveria = {'Avi\'s Restaurant': '₪65',
          'Little Tiberias': '₪65',
          'Decks Restaurant': '₪70',
          'El Rancho': '₪65',
          'Magdalena Restaurant': '₪70',
          'Sin Chan': '₪65',
          'St Urban Wine Bar': '₪70',
          'Galei Gil': '₪75',
          'Hermitage Tiberias': '₪65',
          'Torrance Restaurant': '₪70'}

haifa = {'Quando Pasha': '₪75',
         'Ein ElWadi': '₪70',
         'Falafel Ha\'zkenim': '₪80',
         'Minna Tomei': '₪65',
         'Black Bar N Burger': '₪60',
         'Raffaello Haifa': '₪70',
         'Vivino': '₪70',
         'Ma\'ayan Habira': '₪70',
         'Lux': '₪65',
         'Shtroudl': '₪60'}
